# Generated by Django 4.1.4 on 2023-01-21 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99d90da4-d4f8-4282-b4d5-8a09bd768022'), editable=False, primary_key=True, serialize=False),
        ),
    ]
