# Generated by Django 4.1.4 on 2023-01-21 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_created_at_alter_todo_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_tile',
            new_name='todo_title',
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('08397cd0-b759-4c72-96b5-120864b951a4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
