# Generated by Django 4.1.4 on 2023-01-21 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_todo_tile_todo_todo_title_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('74517cb5-78b2-45d4-ae96-954441c49f1b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
