# Generated by Django 4.1.4 on 2023-01-21 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3a58a3b7-e023-4859-b51c-c8b5e004166b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
