# Generated by Django 4.1.4 on 2023-01-21 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0150410b-5b9c-47ce-a90f-e56b633dc0dd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
