# Generated by Django 4.1.4 on 2023-01-21 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0e5db63f-c339-4612-925a-1ddc5605a5fa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
