# Generated by Django 4.1.4 on 2023-01-22 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_todo_user_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('41b3ca0a-1899-4a3b-9951-de1734289ae5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('41b3ca0a-1899-4a3b-9951-de1734289ae5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
